### ISSUE TITLE
Cannot make elm-format work in Sublime 2

### ISSUE THREAD

**Issue by wintvelt** [avh4/elm-format#285]
Not sure this is the right place for this question, but here goes:
I think I have followed all the instruction steps, including putting elm-format on my Mac (it is in my PATH)

But when I try to run elm-format from Sublime 2.
The console gives the following error:
Traceback (most recent call last):
```
  File "./sublime_plugin.py", line 362, in run_
  File "./elm_format.py", line 26, in run
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 623, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 1141, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
Anyone have any idea how to fix this?

**Comment by avh4** [comment]
Is there a way to verify that the PATH within sublime is correct and contains the path to elm-format?

You could maybe try setting the full path to elm-format in the plugin config and see if that helps.

**Comment by wintvelt** [comment]
thanks for getting back to me. 
Would like to verify and repair, but how can I verify PATH in Sublime?
or set it in "plugin config"?
