### ISSUE TITLE
elm-format exited with code 2

### ISSUE THREAD

**Issue by mark-jordanovic-lewis** [avh4/elm-format#309]
Installed via apm and package manager. Un/Re-installed atom. Paths are correct. OS is Ubuntu 16.04. 

On running atom-beautify I get the error:

```
usr/local/bin/elm-format: 1: /usr/local/bin/elm-format: Syntax error: "(" unexpected
/usr/local/bin/elm-format: 1: /usr/local/bin/elm-format: Syntax error: "(" unexpected
Hide Stack Trace
Error: /usr/local/bin/elm-format: 1: /usr/local/bin/elm-format: Syntax error: "(" unexpected
    at /home/mark/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:295:27
    at tryCatcher (/home/mark/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/mark/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/mark/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/mark/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/mark/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/mark/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/mark/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/home/mark/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

so maybe this is an atom-beautify error? I will report there too.

**Comment by mark-jordanovic-lewis** [comment]
installed using:

```
npm install -g elm-format
```
