### ISSUE TITLE
Error while installing globally

### ISSUE THREAD

**Issue by selbekk** [avh4/elm-format#409]
Hi!

I'm trying to get started with elm-format - because formatting is terrible, and you fine persons fix that for me.

However, when I try to install `elm-format` globally with npm, I get the following error:

```
➜  elm-tutorial sudo npm install -g elm-format
/usr/local/bin/elm-format -> /usr/local/lib/node_modules/elm-format/bin/elm-format

> elm-format@0.6.1-alpha install /usr/local/lib/node_modules/elm-format
> binwrap-install

fs.js:652
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open 'bin/elm-format'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at /usr/local/lib/node_modules/elm-format/node_modules/binwrap/install.js:17:8
    at Array.forEach (native)
    at install (/usr/local/lib/node_modules/elm-format/node_modules/binwrap/install.js:15:19)
    at Object.install (/usr/local/lib/node_modules/elm-format/node_modules/binwrap/index.js:8:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/elm-format/node_modules/binwrap/bin/binwrap-install:16:9)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elm-format@0.6.1-alpha install: `binwrap-install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the elm-format@0.6.1-alpha install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Looks like this might be a problem with `avh4/binwrap`, but since it happened while installing this package, I'm filing the issue here.

I'm running MacOSX (latest stable), and:

```
➜  elm-tutorial node -v
v8.2.1
➜  elm-tutorial npm -v
5.4.2
```

**Comment by selbekk** [comment]
Ah, I see there's an open issue [here](https://github.com/avh4/elm-format/issues/377) - closing this one.

Installing it with yarn worked for my purposes =)
