### ISSUE TITLE
elm-format not working on Mac

### ISSUE THREAD

**Issue by babakness** [avh4/elm-format#436]
Command:
```$ elm-format main.elm```

Error:
```
internal/child_process.js:325
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at Object.<anonymous> (/Users/me/.nvm/versions/node/v8.2.1/lib/node_modules/elm-format/bin/elm-format:4:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
```

**Comment by wende** [comment]
Same here

**Comment by rtfeldman** [comment]
Here's the fix!

https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by kachkaev** [comment]
@babakness does it work now? Feel free to close this issue if yes 😉  

What was the solution?
